apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
stringData:
  DB_HOST: mysql-cluster.mysql.svc.cluster.local
  DB_PORT: "6446"
  DB_USER: appuser
  DB_PASSWORD: AppUserPass123!
  DB_NAME: appdb

