apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: ebs.csi.aws.com
parameters:
  type: gp3   # gp2/gp3 based on your need
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
