apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  DB_HOST: bXlzcWwtc2VydmljZQ== # base64 encoded value of 'mysql-service'
  DB_USER: cm9vdA== # base64 encoded value of 'root'
  DB_PASSWORD: cGFzc3dvcmQ= # base64 encoded value of 'password'
  DB_NAME: dGVzdF9kYg== # base64 encoded value of 'test_db'
