apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  DB_USER: cm9vdA==         # base64 of "root"
  DB_PASSWORD: cGFzc3dvcmQ= # base64 of "password"
  DB_NAME: dGVzdF9kYg==     # base64 of "test_db"
