apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-db
  namespace: mysql
spec:
  backoffLimit: 5
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mysql-init
        image: mysql:8.0
        imagePullPolicy: IfNotPresent

        env:
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-secret
              key: rootPassword

        command:
        - /bin/sh
        - -c
        - |
          echo "Waiting for MySQL Router..."

          until mysql \
            -h mysql-cluster.mysql.svc.cluster.local \
            -P 6446 \
            -u"$MYSQL_USER" \
            -p"$MYSQL_PASSWORD" \
            -e "SELECT 1" >/dev/null 2>&1; do
              echo "MySQL Router not ready yet..."
              sleep 5
          done

          echo "Initializing database and app user..."

          mysql \
            -h mysql-cluster.mysql.svc.cluster.local \
            -P 6446 \
            -u"$MYSQL_USER" \
            -p"$MYSQL_PASSWORD" <<EOF
          CREATE DATABASE IF NOT EXISTS appdb;

          CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY 'AppUserPass123!';

          GRANT ALL PRIVILEGES ON appdb.* TO 'appuser'@'%';

          FLUSH PRIVILEGES;
          EOF

          echo "Database and user initialization complete."

