apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: email-alerts
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 1h

    receivers:
    - name: email-alerts
      email_configs:
      - to: destination-email@example.com
        from: your-email@gmail.com
        smarthost: smtp.gmail.com:587
        auth_username: your-email@gmail.com
        auth_password_file: /etc/alertmanager/secrets/smtp-password
        send_resolved: true

