---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: default
type: Opaque
stringData:
  data-source-name: "root:password@(mysql:3306)/test_db"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: default
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.15.0
        ports:
        - name: metrics
          containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-secret
              key: data-source-name
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: default
  labels:
    app: mysql-exporter
spec:
  ports:
  - name: metrics
    port: 9104
    targetPort: metrics
  selector:
    app: mysql-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-exporter
  namespace: default
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  endpoints:
  - port: metrics
    interval: 30s

