---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-exporter-secret
  namespace: default
type: Opaque
stringData:
  # ✅ Correct DSN format for mysqld-exporter
  data-source-name: "root:password@tcp(mysql.default.svc.cluster.local:3306)/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-exporter
  namespace: default
  labels:
    app: mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-exporter
  template:
    metadata:
      labels:
        app: mysql-exporter
    spec:
      containers:
      - name: mysql-exporter
        image: prom/mysqld-exporter:v0.15.0
        ports:
        - name: metrics
          containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-exporter-secret
              key: data-source-name
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: default
  labels:
    app: mysql-exporter
spec:
  ports:
  - name: metrics
    port: 9104
    targetPort: metrics
  selector:
    app: mysql-exporter
