apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-ld-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-ld-exporter
  template:
    metadata:
      labels:
        app: mysql-ld-exporter
    spec:
      containers:
      - name: mysqld-exporter
        image: prom/mysqld-exporter:v0.15.1
        ports:
        - name: metrics
          containerPort: 9104
        env:
        - name: DATA_SOURCE_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: datasource
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-ld-exporter
  namespace: monitoring
  labels:
    app: mysql-ld-exporter
spec:
  selector:
    app: mysql-ld-exporter
  ports:
  - name: metrics
    port: 9104
    targetPort: metrics

