---
apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-metrics
  namespace: nginx-gateway
  labels:
    app: nginx-gateway
spec:
  ports:
  - name: metrics
    port: 10254
    targetPort: 10254
  selector:
    app.kubernetes.io/name: nginx-gateway
    app.kubernetes.io/component: controller

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway-metrics
  namespace: nginx-gateway
  labels:
    release: prometheus   # must match your Prometheus Helm release
spec:
  selector:
    matchLabels:
      app: nginx-gateway
  namespaceSelector:
    matchNames:
    - nginx-gateway
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

