apiVersion: v1
kind: Service
metadata:
  name: nginx-gateway-metrics
  namespace: nginx-gateway
  labels:
    app: nginx-gateway
spec:
  selector:
    app.kubernetes.io/name: nginx-gateway
  ports:
  - name: metrics
    port: 9113
    targetPort: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-gateway
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
    - nginx-gateway
  selector:
    matchLabels:
      app: nginx-gateway
  endpoints:
  - port: metrics
    interval: 30s

