apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app-servicemonitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: app
  namespaceSelector:
    matchNames:
    - default
  endpoints:
  - port: http
    interval: 30s

