apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql-app
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/CharanSai8127/Node.js-app.git
    targetRevision: HEAD
    path: mysql-innodb
  destination:
    server: https://kubernetes.default.svc
    namespace: mysql
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
