apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: mysql-cluster
  namespace: mysql
spec:
  # Use 3 instances for stable quorum
  instances: 3

  # Root credentials (must exist already)
  secretName: mysql-root-secret

  # Operator-managed internal TLS
  tlsUseSelfSigned: true

  # MySQL Router
  router:
    instances: 1

  # Persistent storage configuration
  datadirVolumeClaimTemplate:
    accessModes:
      - ReadWriteOnce
    storageClassName: standard
    resources:
      requests:
        storage: 1Gi

  # Pod placement (optional but safe)
  podSpec:
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                mysql.oracle.com/cluster: mysql-cluster
                mysql.oracle.com/component: mysqld
            topologyKey: kubernetes.io/hostname

